spring:
  application:
    name: freelanceflow-api
  datasource:
    url: jdbc:postgresql://localhost:5433/freelanceflow
    username: freelanceflow
    password: freelanceflow
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/freelanceflow
          jwk-set-uri: http://localhost:8180/realms/freelanceflow/protocol/openid-connect/certs

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  oAuthFlow:
    authorizationUrl: http://localhost:8180/realms/freelanceflow/protocol/openid-connect/auth
    tokenUrl: http://localhost:8180/realms/freelanceflow/protocol/openid-connect/token
