package nl.itqaanconsulting.freelanceflow.invoice;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import nl.itqaanconsulting.freelanceflow.shared.ResourceNotFoundException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

@Service
class InvoicePdfService {

    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ISO_LOCAL_DATE;

    private final InvoiceRepository invoiceRepository;

    InvoicePdfService(InvoiceRepository invoiceRepository) {
        this.invoiceRepository = invoiceRepository;
    }

    @Transactional(readOnly = true)
    InvoicePdf generate(UUID invoiceId) {
        Invoice invoice = invoiceRepository.findById(invoiceId)
                .orElseThrow(() -> new ResourceNotFoundException("Invoice not found: " + invoiceId));

        ByteArrayOutputStream output = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4, 36, 36, 40, 36);

        try {
            PdfWriter.getInstance(document, output);
            document.open();
            addHeader(document, invoice);
            addInvoiceDetails(document, invoice);
            addLines(document, invoice);
            addFooter(document, invoice);
        } catch (DocumentException exception) {
            throw new IllegalStateException("Could not generate invoice PDF", exception);
        } finally {
            document.close();
        }

        return new InvoicePdf(invoice.getInvoiceNumber() + ".pdf", output.toByteArray());
    }

    private void addHeader(Document document, Invoice invoice) {
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
        Font subtitleFont = FontFactory.getFont(FontFactory.HELVETICA, 10);

        Paragraph title = new Paragraph("FreelanceFlow Invoice", titleFont);
        title.setSpacingAfter(6);
        document.add(title);

        Paragraph subtitle = new Paragraph("Invoice " + invoice.getInvoiceNumber(), subtitleFont);
        subtitle.setSpacingAfter(20);
        document.add(subtitle);
    }

    private void addInvoiceDetails(Document document, Invoice invoice) {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setSpacingAfter(20);

        addLabelValue(table, "Customer", invoice.getProject().getCustomer().getCompanyName());
        addLabelValue(table, "Project", invoice.getProject().getName());
        addLabelValue(table, "Issue date", invoice.getIssueDate().format(DATE_FORMAT));
        addLabelValue(table, "Due date", invoice.getDueDate().format(DATE_FORMAT));
        addLabelValue(table, "Status", invoice.getStatus().name());
        addLabelValue(table, "Currency", invoice.getCurrency());

        document.add(table);
    }

    private void addLines(Document document, Invoice invoice) {
        PdfPTable table = new PdfPTable(new float[]{2.0f, 5.0f, 1.5f, 2.0f, 2.0f});
        table.setWidthPercentage(100);
        table.setSpacingAfter(16);

        addHeaderCell(table, "Date");
        addHeaderCell(table, "Description");
        addHeaderCell(table, "Hours");
        addHeaderCell(table, "Rate");
        addHeaderCell(table, "Amount");

        for (InvoiceLine line : invoice.getLines()) {
            addCell(table, line.getWorkDate().format(DATE_FORMAT), Element.ALIGN_LEFT);
            addCell(table, line.getDescription(), Element.ALIGN_LEFT);
            addCell(table, formatMoney(line.getHours()), Element.ALIGN_RIGHT);
            addCell(table, formatMoney(line.getHourlyRate()), Element.ALIGN_RIGHT);
            addCell(table, formatMoney(line.getLineAmount()), Element.ALIGN_RIGHT);
        }

        document.add(table);
    }

    private void addFooter(Document document, Invoice invoice) {
        Font totalFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
        Paragraph total = new Paragraph(
                "Total: " + invoice.getCurrency() + " " + formatMoney(invoice.getTotalAmount()),
                totalFont
        );
        total.setAlignment(Element.ALIGN_RIGHT);
        total.setSpacingAfter(24);
        document.add(total);

        Font noteFont = FontFactory.getFont(FontFactory.HELVETICA, 9);
        Paragraph note = new Paragraph("Generated by FreelanceFlow API.", noteFont);
        document.add(note);
    }

    private void addLabelValue(PdfPTable table, String label, String value) {
        Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);
        Font valueFont = FontFactory.getFont(FontFactory.HELVETICA, 10);

        PdfPCell labelCell = new PdfPCell(new Phrase(label, labelFont));
        labelCell.setBorder(PdfPCell.NO_BORDER);
        labelCell.setPaddingBottom(6);
        table.addCell(labelCell);

        PdfPCell valueCell = new PdfPCell(new Phrase(value, valueFont));
        valueCell.setBorder(PdfPCell.NO_BORDER);
        valueCell.setPaddingBottom(6);
        table.addCell(valueCell);
    }

    private void addHeaderCell(PdfPTable table, String value) {
        Font font = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);
        PdfPCell cell = new PdfPCell(new Phrase(value, font));
        cell.setHorizontalAlignment(Element.ALIGN_LEFT);
        cell.setPadding(6);
        table.addCell(cell);
    }

    private void addCell(PdfPTable table, String value, int alignment) {
        Font font = FontFactory.getFont(FontFactory.HELVETICA, 10);
        PdfPCell cell = new PdfPCell(new Phrase(value, font));
        cell.setHorizontalAlignment(alignment);
        cell.setPadding(6);
        table.addCell(cell);
    }

    private String formatMoney(BigDecimal value) {
        return value.setScale(2, RoundingMode.HALF_UP).toPlainString();
    }
}
